/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package temperatureconverter;

/**
 *
 * @author AnandRajan
 */

import java.awt.event.*;
import javax.swing.JFrame;

public class TempConverter extends javax.swing.JFrame {

    /**
     * Creates new form TempConverter
     */
    public TempConverter() {
        initComponents();
        initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnsChooseTemp = new javax.swing.ButtonGroup();
        inputField = new javax.swing.JTextField();
        btnConvert = new javax.swing.JButton();
        btnToCelsius = new javax.swing.JRadioButton();
        btnToFahr = new javax.swing.JRadioButton();
        appLabel = new javax.swing.JLabel();
        chooseLabel = new javax.swing.JLabel();
        enterConvertLabel = new javax.swing.JLabel();
        tempConvertLabel = new javax.swing.JLabel();
        outputLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputField.setToolTipText("Enter a temperature in the chosen degrees");
        inputField.setSize(new java.awt.Dimension(63, 24));
        inputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFieldActionPerformed(evt);
            }
        });

        btnConvert.setText("Convert Temperature");
        btnConvert.setToolTipText("");

        btnsChooseTemp.add(btnToCelsius);
        btnToCelsius.setText("Fahrenheit to Celsius");

        btnsChooseTemp.add(btnToFahr);
        btnToFahr.setText("Celsius to Fahrenheit");

        appLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        appLabel.setForeground(new java.awt.Color(222, 0, 0));
        appLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appLabel.setText("Temperature Converter");
        appLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        chooseLabel.setText("Choose Conversion Type:");

        enterConvertLabel.setText("Enter the temperature to convert:");

        tempConvertLabel.setText("The temperature converts to:");

        outputLabel.setText("Nothing converted yet");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterConvertLabel)
                    .addComponent(tempConvertLabel))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(outputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputField, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addGap(0, 87, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(appLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(chooseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnToFahr)
                            .addComponent(btnToCelsius)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(btnConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(appLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(chooseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnToCelsius)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnToFahr)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(enterConvertLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempConvertLabel)
                    .addComponent(outputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addComponent(btnConvert)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TempConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TempConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TempConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TempConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TempConverter().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appLabel;
    private javax.swing.JButton btnConvert;
    private javax.swing.JRadioButton btnToCelsius;
    private javax.swing.JRadioButton btnToFahr;
    private javax.swing.ButtonGroup btnsChooseTemp;
    private javax.swing.JLabel chooseLabel;
    private javax.swing.JLabel enterConvertLabel;
    private javax.swing.JTextField inputField;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JLabel tempConvertLabel;
    // End of variables declaration//GEN-END:variables
    private double tempInput, tempOutput;
    
    private void initialize(){
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setTitle("Temperature Converter");
        
        tempConvertLabel.setVisible(false);
        outputLabel.setVisible(false);
        
        Handler tempHandler = new Handler();
        btnConvert.addActionListener(tempHandler);
    }
    
    
    public class Handler implements ActionListener{
        
        @Override
        public void actionPerformed(ActionEvent evt){
            if (evt.getSource() == btnConvert){
                
                tempConvertLabel.setVisible(true);
                outputLabel.setVisible(true);
                
                String strInput = inputField.getText();
                
                try{
                    Double.parseDouble(strInput);
                }
                
                catch(NumberFormatException e){
                    javax.swing.JOptionPane.showMessageDialog(null, "Only numeric values should be entered.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                catch(Exception e){
                    javax.swing.JOptionPane.showMessageDialog(null, "Exception occurred.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    return;
                }
                tempInput = Double.parseDouble(strInput);
                
                if (btnToCelsius.isSelected()){
                    handleBtnToCelsius();
                }
                else if (btnToFahr.isSelected()){
                    handleBtnToFahr();
                }
                else{
                    System.out.println("No conversion was selected");
                }
            }
            
            else {
                System.out.println("Something went wrong!");
            }
        }
        
        public void handleBtnToCelsius(){
            tempOutput = (tempInput - 32) * (5.0/9.0);
            String strOutput = String.format("%.1f degrees Celsius", tempOutput);
            outputLabel.setText(strOutput);
        }
        
        
        public void handleBtnToFahr(){
            tempOutput = ((9.0 * tempInput)/5.0) + 32.0;
            String strOutput = String.format("%.1f degrees Fahrenheit", tempOutput);
            outputLabel.setText(strOutput);
        }
    }
}

